server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmq_example?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&serverTimezone=America/Los_Angeles&allowMultiQueries=true
    username: root
    password: lt2015196
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
    properties:
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_size: 1000
  # RabbitMq
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

swagger:
  name: spring boot rabbitmq example project
  title: spring boot rabbitmq example interface
  author: stackstone
  url: ...
  email: ...
  description: spring boot rabbitmq example project
  version: 1.0.0
