server:
  port: 8585
  servlet:
    context-path: /circuitBreaker
  tomcat:
    threads:
      # 最大工作线程数，默认200。（4核8g内存，线程数800，一般是核数*200。操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。）
      max: 20
      # 最小工作空闲线程数，默认10。（适当增大一些，以便应对突然增长的访问量）
      min-spare: 20
    #最大连接数，默认为10000
    max-connections: 20
    # 等待队列长度，默认100。队列也做缓冲池用，但也不能无限长，不但消耗内存，而且出队入队也消耗CPU
    accept-count: 20
spring:
  application:
    name: circuitBreaker